#!/usr/bin/env python

"Generate a lock file"

import sys
import struct

if sys.argv < 3:
	print "Use: mklock filename number"
	sys.exit(1)

try:
	n = int(sys.argv[2])
except:
	print "Use: mlock filename number"
	sys.exit(1)

fd = open(sys.argv[1], "w");

s = struct.pack("I", n)

fd.write(s)

fd.close()

