#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: prerelease RELNUM"
	exit
fi

echo "Creating the full patch"
patchdesc $(cat ps/series) > ../libjio-$1.patch
patchdesc $(cat ps/series) > ../Changelog-$1
echo >> ../libjio-$1.patch
echo >> ../libjio-$1.patch
combine-series ../libjio-$1-t1.patch
cat ../libjio-$1-t1.patch >> ../libjio-$1.patch
rm ../libjio-$1-t1.patch

echo "Cleaning up"
make clean

